### PR TITLE
chore(cardano): remove legacy signing

### PR DESCRIPTION
**Pull request by davidmisiak**
This PR removes `cardanoSignTransaction` support for firmware versions that do not support transaction streaming (<2.4.2), as agreed [here](https://github.com/trezor/connect/pull/841#issuecomment-905454740).

We have removed the legacy types from firmware ([PR](https://github.com/trezor/trezor-firmware/pull/2228)). Should we also open a PR to [@trezor/transport](https://github.com/trezor/trezor-suite/tree/develop/packages/transport), or will the type updates be performed automatically when the firmware submodule is updated?

### CODE REVIEW

**Comment by mroz22** [comment]
Hi, thanks for contribution. 
We have moved trezor-connect into trezor/trezor-suite monorepo now. And I have recreated this PR there https://github.com/trezor/trezor-suite/pull/5426

We are going to mantain trezor-connect version 8 for a while thats for sure but I am thinking about not removing legacy signing in version 8 and doing it only in version 9 only (that we are about to release soon)

**Comment by davidmisiak** [comment]
Thank you for taking care of this.

> We have moved trezor-connect into trezor/trezor-suite monorepo now.

Does that mean we should open future PRs (e.g. with new Cardano features) in the trezor-suite repo from now on?

**Comment by sime** [comment]
> Does that mean we should open future PRs (e.g. with new Cardano features) in the trezor-suite repo from now on?

Yes, that is the plan.

**Comment by mroz22** [comment]
This PR has been merged into trezor-suite monorepo already. So I am closing it here as we do not plan any maintanance or adding new features for cardano in connect version 8

**Pull request closed without merging**
