### PR TITLE
Feature/ethereum message hex

### PR DESCRIPTION
**Pull request by szymonlesisz**

### CODE REVIEW

**Comment by szymonlesisz** [comment]
will be released in 5.0.32

**Comment by cavanmflynn** [comment]
Thanks, @szymonlesisz! I pulled down `5.0.32`, but I am running into the same issue. Any ETA to get the code at connect.trezor.io updated?

**Comment by szymonlesisz** [comment]
I've wrote this as a comment on your [PR](https://github.com/trezor/connect/pull/215#issuecomment-422326127). It will be probably today

**Comment by cavanmflynn** [comment]
Sorry to keep pushing on this @szymonlesisz, but we are completely blocked until this is deployed. Do you have a more concrete release date as yesterday has come and gone? Thanks!

**Comment by szymonlesisz** [comment]
released, should be working now

**Pull request merged**
