### PR TITLE
Allow to sign transactions without backend (#369)

### PR DESCRIPTION
**Pull request by JonSalazar**
Allow to sign self-contained transactions even if the coin has no backend

### CODE REVIEW

**Comment by szymonlesisz** [comment]
Looks easy, but unfortunately this is not the right place for this change.
If it not fail here it will fail in next step, inside `hd-wallet` (blockbook communication socket) and throw "Backend is offline" error.

To allow signing transaction for bitcoin-like coins without specified backend there must be several other changes:
1. add this coin to `trezor-common` and set support for connect
2. build coins.json from `trezor-common`
3. use `signTransaction` method with `refTxs` field set. There is already condition for not using backend at all if this field is set [here](https://github.com/trezor/connect/blob/develop/src/js/core/methods/SignTransaction.js#L145-L153)

**Comment by AlexITC** [comment]
@szymonlesisz 

- Our coin is already in `trezor-common` with connect enabled (see https://github.com/trezor/connect/commit/d3a9e8508ab74d05087b84c1b4ebb8a9fa265fc7).
- From what I see, you already built the coins.json (https://github.com/trezor/connect/commit/d3a9e8508ab74d05087b84c1b4ebb8a9fa265fc7).
- The problem that I see on `signTransaction`, is that it will crash when there is no backend nor the reference transactions, we could add a conditional to enforce the reference transactions when there is no backend available, do you have a better idea?

We have already signed a transaction for XSN by providing all the reference transactions and the only change was what is included in this PR.

Thanks.

**Comment by prusnak** [comment]
@AlexITC: Citing https://github.com/trezor/trezor-common/pull/302#issuecomment-477202697

> "from what I understand, we can call signTransaction passing all the arguments which avoids requiring any backend on the json"

So this is exactly what you need to do. If you want to use the backend functionality provided by the Connect, you need to provide the blockbook backend. That is all.

**Comment by JonSalazar** [comment]
You're right, the change is unnecessary, thanks.

**Pull request closed without merging**
