### PR TITLE
capricoin: added more tests

### PR DESCRIPTION
**Pull request by Adman**
Signed-off-by: Adrian Matejov <ado.matejov@gmail.com>

### CODE REVIEW

**Comment by Adman** [comment]
@szymonlesisz Hi, I've added some more test cases (except p2sh, because CPC does not support it), but I'm still unable to run these tests locally. Can you test it yourself, please?

```
LOG: '- Running /oneTwoFee ...'
WARN: Object{event: 'RESPONSE_EVENT', type: 'RESPONSE_EVENT', id: 1, success: false, payload: Object{error: 'Transport is missing'}}
ERROR: 'Cannot load debugLink state', 'Transport is missing'
ERROR: 'Unhandled promise rejection', TypeError: can't convert undefined to object
```

**Comment by szymonlesisz** [comment]
Since capricoin doesn't support segwit shouldnt these two lines: https://github.com/trezor/trezor-common/blob/master/defs/bitcoin/capricoin.json#L17-L18 be set to null?

**Comment by prusnak** [comment]
@szymonlesisz i will fix that, thanks

**Comment by Adman** [comment]
@prusnak thanks for fixing it

@szymonlesisz is there anything more I can do?

**Pull request merged**
