### PR TITLE
Tezos integration

### PR DESCRIPTION
**Pull request by jurajselep**

### CODE REVIEW

**Comment by prusnak** [comment]
Don't merge unless https://github.com/trezor/trezor-common/pull/139 is merged first

**Comment by szymonlesisz** [comment]
Hi @jurajselep ,
Since we are not going to add new logic to v4 i wanted to rewrite this PR to trezor-connect v5, but i noticed that your PR from [trezor.js](https://github.com/trezor/trezor.js/pull/62/files) does not match protobuf messages at all and throws error.

Please rewrite "TezosSignTx" logic on trezor-connect v5 codebase
and add some docs with examples to it

**Comment by szymonlesisz** [comment]
I've prepared a branch with Tezos methods for you:

https://github.com/trezor/connect/tree/feature/tezos

where tezosGetAddress and tezosGetPublicKey should already work

You need to complete tezosSignTransaction method by adding:
1. correct types for tezos transaction in: 
- ./src/js/types/tezos.js where you should use field names compatible with tezos javascript sdk
- ./src/js/types/trezor.js where you shoud field names declared in protobuf

2. sign transaction logic in ./src/js/core/methods/helpers/tezosSignTx.js where you should translate incoming transaction from "sdk-type" to "protobuf-type" and also handle ACK called from device. You can get inspired by stellarSignTx helper for example

3. add documentation with examples

4. write some tests

**Comment by jurajselep** [comment]
Thanks,
 I already started in local repository

**Comment by szymonlesisz** [comment]
sorry for duplicating your work :)
I already did most it, so please look at my commits in feature/tezos branch and follow instructions above

**Comment by jurajselep** [comment]
I refactored "TezosSignTx" and added  types  https://github.com/trezor/connect/pull/208
I will add tests and documentation with examples.

**Pull request closed without merging**
