### PR TITLE
tests(stellar): add stellar test with sequence over MAX_SAFE_INTEGER

### PR DESCRIPTION
**Pull request by mroz22**
Hi @overcat 
I just added your test fixture from #970 (starting on line 208) and it did pass. :thinking:
Is my fixture correct? If yes, we need to find out why it did not work for you :thinking:

### CODE REVIEW

**Comment by overcat** [comment]
This test looks good.

I have prepared an [html page](https://gist.github.com/overcat/a7dc1c376f6d4415430a038a1a6ca3da), you can try to run it locally to see if you can get the correct signature.

The browser version I use is: Google Chrome Version 96.0.4664.93 (Official Build) (arm64) / Firefox 94.0.2

**Comment by overcat** [comment]
That test case failed, it got the same wrong signature
```
Chrome 96.0.4664.45 (Linux x86_64) TrezorConnect methods TrezorConnect.stellarSignTransaction Sequence is over Number.MAX_SAFE_INTEGER and is sent as string FAILED
	Error: Expected $.payload.signature = '066adaa0fcdb9faf6752407b05ef2c13060ba94d1f9146c136febaab7301a773a9ef3d858899de6a8943e433df704b2f01b69698e21efccf56468208a4f3930f' to equal '5f0ab0eb1468da93fb994138c9b431bd8cbb4f8b581eaf18ba822567952a9f233bd3ef0f21fff02851b3158da40550a849c610941cd1f65a291f75681e22fe0c'.
	    at <Jasmine>
	    at compare (webpack://trezor-connect/./tests/karma.setup.js?:47:26)
	    at <Jasmine>
Chrome 96.0.4664.45 (Linux x86_64): Executed 29 of 34 (1 FAILED) (0 secs / 2 mins 33.4 secs)
```
```python
>>> base64.b64encode(binascii.unhexlify('066adaa0fcdb9faf6752407b05ef2c13060ba94d1f9146c136febaab7301a773a9ef3d858899de6a8943e433df704b2f01b69698e21efccf56468208a4f3930f'))
b'BmraoPzbn69nUkB7Be8sEwYLqU0fkUbBNv66q3MBp3Op7z2FiJneaolD5DPfcEsvAbaWmOIe/M9WRoIIpPOTDw=='
>>> base64.b64encode(binascii.unhexlify('5f0ab0eb1468da93fb994138c9b431bd8cbb4f8b581eaf18ba822567952a9f233bd3ef0f21fff02851b3158da40550a849c610941cd1f65a291f75681e22fe0c'))
b'Xwqw6xRo2pP7mUE4ybQxvYy7T4tYHq8YuoIlZ5UqnyM70+8PIf/wKFGzFY2kBVCoScYQlBzR9lopH3VoHiL+DA=='
>>> 
```

**Comment by mroz22** [comment]
Yes. it seems to be failing in browser environment. Great.

**Comment by mroz22** [comment]
Closing in favor of #974

**Pull request closed without merging**
