### PR TITLE
Add support for Cardano

### PR DESCRIPTION
**Pull request by ddeath**
This PR is for adding Cardano currency support and is intended to merge with https://github.com/trezor/trezor-core/pull/250 and https://github.com/trezor/trezor.js/pull/65

For the support of Cardano currency was required to add cardano-specific ed25519 crypto support.
The crypto code is based on [cardano-crypto](https://github.com/input-output-hk/cardano-crypto) and [cardano-sl](https://github.com/input-output-hk/cardano-sl) - official Cardano repos.

We are NOT official developers of Cardano, however we are developers of [www.cardanolite.com](https://www.cardanolite.com)

### CODE REVIEW

**Comment by prusnak** [comment]
Do not merge unless https://github.com/trezor/trezor-common/pull/148 is merged first

**Comment by ddeath** [comment]
Hello, could you please update status on this PR. Do we have to do something to get this to merge? Thank you

**Comment by prusnak** [comment]
Please rebase the patch against the develop branch and send a PR to this
branch. This PR is against v4 branch which is the older one (latest
stable is v5).

**Comment by szymonlesisz** [comment]
Ported to version 5. [PR] https://github.com/trezor/connect/pull/186

A few changes was made:

1. CardanoSignTransaction amounts should be a string
2. Expected params and responses retyped from snake_case to camelCase
3. CardanoGetPublicKey & CardanoGetAddress merged as one method "TrezorConnect.cardanoGetAddress"

Please see the docs and let me know what you think:

https://github.com/trezor/connect/blob/feature/cardano/docs/methods/cardanoGetAddress.md
https://github.com/trezor/connect/blob/feature/cardano/docs/methods/cardanoSignTransaction.md
https://github.com/trezor/connect/blob/feature/cardano/docs/methods/cardanoSignMessage.md
https://github.com/trezor/connect/blob/feature/cardano/docs/methods/cardanoVerifyMessage.md

**Comment by ddeath** [comment]
@szymonlesisz first of all thank you for porting it to v5.

I suggest not to merge getAddress and getPublicKey because:

* showOnTrezor paremeter will not work as the exporting of public key must be confirmed on trezor device, so bundling addresses to get them exported will not work as you will have to confirm exporting the key for each address
* also public key is exporting hdPassphrase which is little bit sensitive - with this passphrase you will be able to tell if given address is belonging to the same wallet... if you do not have that passphrase you wont be able to say that. If the methods are merged, you will lost the ability to not share that passphrase

**Comment by ddeath** [comment]
@szymonlesisz let me know what you think about that split to the getAddress and getPublicKey I can split it and create PR to your branch

**Comment by szymonlesisz** [comment]
@ddeath ,
Yes, we [agreed](https://github.com/trezor/trezor-core/issues/308#issuecomment-414307796) to split those two methods.
I've updated TrezorConnect code [here](https://github.com/trezor/connect/commit/9756f11b1100cc86834354d49c0b6709a960526b)

**Comment by ddeath** [comment]
Closing this PR in favor of #186

**Pull request closed without merging**
