### PR TITLE
Add support for cardano stake pool registration

### PR DESCRIPTION
**Pull request by refi93**
Motivation: Add support for stakepool registration as owner in Cardano

Depends on https://github.com/trezor/trezor-firmware/pull/1317

### CODE REVIEW

**Comment by refi93** [comment]
@matejcik will this be merged with the upcoming Trezor firmware release? Otherwise the functionality added in https://github.com/trezor/trezor-firmware/pull/1317 won't be accessible via connect

**Comment by matejcik** [comment]
cc @tsusanka

**Comment by refi93** [comment]
@tsusanka is reviewing/merging of this PR be postponed after Trezor 2.3.5 (with the corresponding features) is released or is there some different blocker that we may help with?

**Comment by szymonlesisz** [comment]
this PR will be merged before end of the year, before 2.3.5 release.
there was [a lot of changes regarding types](https://github.com/trezor/connect/pull/728) of protobuf messages, so it needs to be merged first. (cardano affected)
then there is [another big PR](https://github.com/trezor/connect/pull/734) with a new set of protobuf messages (2.3.5) including new cadano messages (CardanoPoolParametersType)
then i'll rebase this branch, solve potential conflicts (messages.json etc) and merge it

thanks for patience :)

**Comment by refi93** [comment]
@szymonlesisz are connect PRs being merged independently of the upcoming trezor-firmware code freeze? Did any blocker to merge this PR appear since your last reply?

**Comment by szymonlesisz** [comment]
closing via https://github.com/trezor/connect/pull/746
reverted the changes in messages.json and protobuf types (types are generated automatically from json) 

thanks!

**Pull request closed without merging**
