### PR TITLE
fix: TrezorConnect.firmwareUpdate method

### PR DESCRIPTION
**Pull request by marekrjpolak**
- uploaded binary modified in the same way as when downloaded by version
- Rollout version 1.2.0 needed

### CODE REVIEW

**Comment by marekrjpolak** [comment]
Looks good, everything I need is there.

**Review by mroz22 — APPROVED** [review]
looks good

**Review by tomasklim — APPROVED** [review]

**Comment by tsusanka** [comment]
I think this will conflict with https://github.com/trezor/trezor-suite/pull/4038/files. Which one should we merge first?

**Comment by tsusanka** [comment]
Gitlab is failing because someone sent money to [this address](https://etherscan.io/address/0x3f2329C9ADFbcCd9A84f52c906E936A42dA18CB8) and we check its balance. There is already [pending tx](https://etherscan.io/tx/0x50ca4d1086ec7cc6b17ab57658993da84e2ae22770ee417bea22303c518fe45c) that will solve this so I am gonna ignore it for now but it is not a good idea to depend on such externality and someone could troll us very easily this way. I believe we should mock this.

**Pull request merged**
