### PR TITLE
Update stellar types for stellar V11 (launching Monday June 3rd)

### PR DESCRIPTION
**Pull request by istrau2**
Adds additional types for Stellar v11 (going to production Monday June 3rd). Please see here:
https://github.com/stellar/js-stellar-base/blob/master/src/generated/stellar-xdr_generated.js#L2175

@fnando Do these changes look good to you? What about the legacy ops (i.e. manageOffer, createPassiveOffer), will those still work past Monday?

### CODE REVIEW

**Comment by szymonlesisz** [comment]
Hi @istrau2, 
Thanks for contribution, but those additional operations should be added to the firmware at the first place so Trezor device will be able to understand them. Adding types to trezor-connect is not enough.

**Comment by istrau2** [comment]
@szymonlesisz Understood. This was more my way of introducing the issue (i.e. instead of just creating an issue, I thought I could start a PR).

I actually don't know how the upgrade to the network (planned for this Monday), will impact the current trezor sdk...

**Comment by theaeolianmachine** [comment]
@szymonlesisz we have delayed the date until June 10th — what's the process of getting Trezor support when the network upgrades? The potential problems to come up seem to be:

* We added an additional operation (`ManageBuyOffer`), which if not supported users will not be able to utilize.
* We renamed two operations, which are are almost binary compatible but because of the change of offer IDs from uint64 to int64's, without changes this is likely to cause unexpected behavior.

We would highly advocate for making sure Trezor is compatible with Stellar V11's changes before the public network switches over on `2019-06-10 1600 UTC`.

Please feel free to [reach out to me on Keybase](https://keybase.io/aeolianmachine) with any questions you may have.

**Comment by prusnak** [comment]
@theaeolianmachine Trezor firmware is released on the first Wednesday of a month and freezed two weeks prior that. Your changes will not fit in the June update, but they might fit in the July update if you send them soon enough. I suggest you send a pull request to our firmware monorepo: https://github.com/trezor/trezor-firmware before the next freeze. There are two types of firmware - legacy (T1) and core (T2), so please update both. Thank you!

**Comment by prusnak** [comment]
Closing. As per the explanation above, the types need to be changed in the firmware repo first.

**Pull request closed without merging**
