### PR TITLE
Add network param and remove signMsg and verify msg from cardano

### PR DESCRIPTION
**Pull request by ddeath**
Removed cardano sign message and verify message calls.

Added new network parameter to cardano sign tx and also updated test data for signing transaction.

Please wait until https://github.com/trezor/trezor-common/pull/205 get merged

Also solving #209

### CODE REVIEW

**Comment by szymonlesisz** [comment]
wow! :) super

**Comment by prusnak** [comment]
https://github.com/trezor/trezor-common/pull/205 is merged

**Comment by ddeath** [comment]
@szymonlesisz can I change the trezor-common submodule to the current master? Asking because the actual trezor-common is ~30 commints behind

**Comment by szymonlesisz** [comment]
I will bump this later today after i merge your PR, i need to make sure that it will not break anything. There were a lot of changes recently

**Comment by ddeath** [comment]
Great thanks.

**Comment by szymonlesisz** [comment]
i've found another issue with this method
other coins has "hold to confirm" button at the last confirmation screen, cardano doesn't.
It's not a big deal but i think it should be fixed due to consistency

**Pull request merged**
