### PR TITLE
Polis info

### PR DESCRIPTION
**Pull request by eabz**
Missing Polis information.

### CODE REVIEW

**Comment by szymonlesisz** [comment]
Hi @eabz,
Unfortunately this is not the right place for this PR.
`coins.json` is a file generated from [trezor-firmware/common](https://github.com/trezor/trezor-firmware/tree/master/common) respository.
You should add your definition to the /defs/bitcoin/ directory and also enable [support](https://github.com/trezor/trezor-firmware/blob/master/common/defs/support.json) for for connect

**Comment by eabz** [comment]
Thanks @szymonlesisz 
But Polis def has been there for a long time: https://github.com/trezor/trezor-firmware/blob/master/common/defs/bitcoin/polis.json
Can you check why this isn't on the coins.json?

**Comment by szymonlesisz** [comment]
it's because"POLIS" support is not added to "connect" https://github.com/trezor/trezor-firmware/blob/master/common/defs/support.json, its added only to the firmware support

**Comment by eabz** [comment]
Thanks @szymonlesisz, I think I'll put an issue on trezor-firmware.

**Pull request closed without merging**
