### PR TITLE
Pr/eip1559

### PR DESCRIPTION
**Pull request by szymonlesisz**
https://github.com/trezor/connect/pull/871 with fixups

### CODE REVIEW

**Review by matejkriz — APPROVED** [review]
Looks good to me. Please check the minimal docs update I made in  1366b419115db4054999830034567f69a9c11fec

**Comment by That3Percent** [comment]
This doesn't seem to be working.

I'm using Remix + MetaMask 10.1.0 (the latest as of today) and Trezor model T with firmware 2.4.2.

The error message I get is this:
"Invalid transaction params: params specify an EIP-1559 transaction but the current network does not support EIP-1559"

**Comment by javimaravillas** [comment]
Has anyone made this work?

**Comment by javimaravillas** [comment]
@That3Percent 
I have been told that the problem is using the last version of metamask. He has been able to make it work with a older version of metamask.

**Comment by That3Percent** [comment]
Yes, I was able to get it to work with MetaMask 9.8.4 and tracked the cause to this issue: [https://github.com/MetaMask/metamask-extension/issues/12130](https://github.com/MetaMask/metamask-extension/issues/12130)

**Comment by 0xGitGuy** [comment]
@matejkriz Take a look at this https://github.com/MetaMask/metamask-extension/issues/12130

**Comment by kfeldspar** [comment]
@matejkriz Not working for me either. I get the same error message, with latest version Metamask and firmware on Trezor. Discussed here MetaMask/metamask-extension#12130

**Comment by matejkriz** [comment]
@0xGitGuy @kfeldspar It needs to be implemented on Metamask side, in the meantime you could try to downgrade Metamask to v9.8.4.

**Comment by 0xGitGuy** [comment]
@matejkriz EIP 1559 was only implemented in 10.0.0. Does it mean downgrading to 9.8.4, we lose type 2 transaction?

**Pull request merged**
