### PR TITLE
fix(stellar): fix PathPaymentStrictSend

### LINKED ISSUE #4890: PathPaymentStrictSend in Connect not working (Stellar)
## Description
When trying to do a PathPaymentStrictSend operation it fails because we're not parsing the parameters "destMin" and "sendAmount" into integers.

## Steps to reproduce
Generate a PathPaymentStrictSend in the Stellar Laboratory and try to sign it with a Trezor Hardware Wallet.

## Additional info
Browser: Chrome, Brave and Firefox
trezor-connect: 8.2.4-extended
Device: Trezor One (fw 1.10.4)

## How to solve
Updating line https://github.com/trezor/connect/blob/6dfb514f2c4de2b7f93e04965572b22918a0fc1d/src/js/plugins/stellar/plugin.js#L103 and including both 'destMin' and 'sendAmount' fix the issue. It will end up like this:
```
const amounts = ['amount', 'sendMax', 'destAmount', 'startingBalance', 'limit', 'buyAmount', 'destMin', 'sendAmount'];
```

PS: I tried to do the Pull request with the fix but it didn't allowed me to do it

### PR DESCRIPTION
**Pull request by tsusanka**
Should close trezor/trezor-suite#4890. Did not build or test, let's see if the tests pass.

### CODE REVIEW

**Comment by mroz22** [comment]
tests are passing right now. BUT this plugin is not under tests anyway so we know nothing. Maybe we could cover it in a similar way we have tests for `plugins/ethereum`

**Comment by szymonlesisz** [comment]
i never had a time for this, but [this](https://github.com/szymonlesisz/trezor-connect-stellarsdk) is the source for `stellar-sdk-plugin` it contains test vectors as well, but needs to be rewriten

**Review by 78877i — APPROVED** [review]
Vip_person1188

**Comment by mroz22** [comment]
https://github.com/trezor/trezor-suite/pull/5450

**Pull request closed without merging**
