### PR TITLE
NEM Support

### PR DESCRIPTION
**Pull request by saleemrashid**
See trezor/trezor-mcu#196

### CODE REVIEW

**Comment by prusnak** [comment]
Yes, please, merge this before ...

**Comment by szymonlesisz** [comment]
Hi @saleemrashid, is there any reason why you put "show_display" parameter into "nemGetAddress" method? 
Im asking because in other "getAddress" methods we always prompt this message before user is asked for PIN and its mandatory, but in your code is optional.
I've just wrote some examples and it returns proper results (same results as in python-trezor tests)

**Comment by saleemrashid** [comment]
@szymonlesisz I think it was because `nemGetAddress` is more similar to `getXpubKey` than `getAddress` (because NEM addresses are reused). But in hindsight, I think we should enforce `show_display` and remove the optional parameter from `nemGetAddress`.

**Comment by saleemrashid** [comment]
Apparently this was merged ad427bf895ca2361dc57fbee8c7add20a37b64e3

**Pull request closed without merging**
